spotify_playlist_url: "https://open.spotify.com/embed/playlist/0Yf7yZwXCw3ADrGIjswsnJ"
itunes_tracks:
  - name: "Lorelei Soundtrack Album"
    url: "https://music.apple.com/us/album/lorelei/6813827128"
  - name: "Lorelei Main Title Studio Theme"
    url: "https://music.apple.com/us/album/lorelei-maintitle-original-studio/6814424937?i=6814424938"
  - name: "Below Gammorah - Cathedral"
    url: "https://music.apple.com/us/album/below-gammorah-cathedral/6815056657?i=6815056658"
  - name: "We Doin' This Now"
    url: "https://music.apple.com/us/album/we-doin-this-now-feat-victoria-quiles/6815332785?i=6815332786"
  - name: "Crazy Clown"
    url: "https://music.apple.com/us/album/crazy-clown-feat-victoria-quiles-single/6816218483"
biographical_sections:
  - name: "Erik Olson"
    title: "Writer, Composer, Producer, and Lead Developer"
    image: "images/eo.jpg"
    description: "Software Developer, Writer, Composer, and Producer - Erik is the principal author of AtomicFlix productions and the lead scientist in charge of all the monsters."
    email: "blackrushdrive@gmail.com"
  - name: "Victoria Quiles"
    title: "Writer, Developer, Vocals & Sound Design"
    image: "images/vq.jpg"
    description: "Software Developer, Writer and Vocalist - Victoria is the voice of the AtomicFlix soundtracks, bringing a unique blend of 80s pop and 90s rock to the soundtrack."
    email: "atomixflix@gmail.com"
  - name: "Ciera Nicole Sheppard"
    title: "Writer, Vocals & Design"
    image: "images/cns.jpg"
    description: "Writer, Vocalist and Costume Designer - Nicole brings a powerful blend of storytelling, character development, costume design, and epic vocals right where it's needed."
    email: "atomixflix@gmail.com"
  - name: "Per Thorson"
    title: "Vocalist, Sound Designer, and Producer"
    image: "images/pt.jpg"
    description: "Story Editor and Vocalist - Per is the voice of the AtomicFlix audio books and 'Watchable Storyboard' contributor"
    email: "pthorson@blackrush.com"
social_links:
  facebook: "https://www.facebook.com/profile.php?id=61593514836175"
  instagram: "https://www.instagram.com/blackrushworld/"
  tiktok: "https://www.tiktok.com/@blackrushworld"
  x: "https://x.com/AtomicFlixCom"
  youtube: "https://youtube.com/blackrush"
  rumble: "https://rumble.com/user/erikleeolson"
  atomicflix: "https://atomicflix.com"