spotify_playlist_url: "https://open.spotify.com/embed/playlist/0Yf7yZwXCw3ADrGIjswsnJ"
itunes_tracks:
  - name: "00 - Lorelei Soundtrack Album"
    url: "https://music.apple.com/us/album/lorelei/6813827128"
  - name: "00 - Lorelei Main Title Studio Theme"
    url: "https://music.apple.com/us/album/lorelei-maintitle-original-studio/6814424937?i=6814424938"
  - name: "08 - Below Gammorah Cathedral"
    url: "https://music.apple.com/us/album/below-gammorah-cathedral/6815056657?i=6815056658"
  - name: "01 - We Doin This Now"
    url: "https://music.apple.com/us/album/we-doin-this-now-feat-victoria-quiles/6815332785?i=6815332786"
  - name: "06 - Crazy Clown"
    url: "https://music.apple.com/us/album/crazy-clown-feat-victoria-quiles-single/6816218483"
  - name: "13 - Villian Vince"
    url: "https://music.apple.com/us/album/villian-vince/6813827128?i=6813827136"
  - name: "16 - Every 80s Movie"
    url: "https://music.apple.com/us/album/every-80s-movie/6813827128?i=6813827134"
  - name: "21 - Eclipse Still Alive"
    url: "https://music.apple.com/us/album/im-still-alive/6816827721?i=6816827722"
  - name: "20 - Crazy Clown Dance Remix"
    url: "https://music.apple.com/us/album/crazier-clown-feat-victoria-quiles/6816239690?i=6816239691"
  - name: "15 - Showdown"
    url: "https://music.apple.com/us/album/showdown/6813827128?i=6813827133"
  - name: "12 - 1987"
    url: "https://music.apple.com/us/album/1987/6813827128?i=6813827130"
  - name: "10 - Nadine"
    url: "https://music.apple.com/us/album/nadine/6813827128?i=6813827138"
  - name: "11 - Hero Journey"
    url: "https://music.apple.com/us/album/hero-journey/6813827128?i=6813827131"
  - name: "17 - Lorelei Theme Salvation Meditation"
    url: "https://music.apple.com/us/album/lorelei-theme-salvation-meditation-feat-victoria-quiles/6815698248?i=6815698249"
  - name: "15 - Night City"
    url: "https://music.apple.com/us/album/night-city/6813827128?i=6813827137"
  - name: "03 - Lorelei Theme Concert Piano"
    url: "https://music.apple.com/us/album/lorelei-piano-title/6814400725?i=6814400726"
  - name: "04- Lorelei Theme Piano Concerto"
    url: "https://music.apple.com/us/album/lorelei-piano-concerto-original-tv-series-soundtrack/6814482434?i=6814482436"
  - name: "19 - We Doin This Again"
    url: "https://music.apple.com/us/album/we-doin-this-again-feat-victoria-quiles/6815304980?i=6815304982"
  - name: "02 - Lorelei Theme Sonata with Vocals"
    url: "https://music.apple.com/us/album/lorelei-theme-sonata-with-vocals/6814891415?i=6814891416"
  - name: "07 - Below Gamorrah - Piano"
    url: "https://music.apple.com/us/album/below-gamorrah-studio-cut/6815057074?i=6815057075"
biographical_sections:
  - name: "Erik Olson"
    title: "Writer, Composer, Producer, and Lead Developer"
    image: "images/eo.jpg"
    description: "Software Developer, Writer, Composer, and Producer - Erik is the principal author of AtomicFlix productions and the lead scientist in charge of all the monsters."
    email: "blackrushdrive@gmail.com"
  - name: "Victoria Quiles"
    title: "Writer, Developer, Vocals & Sound Design"
    image: "images/vq.jpg"
    description: "Software Developer, Writer and Vocalist - Victoria is the voice of the AtomicFlix soundtracks, bringing a unique blend of 80s pop and 90s rock to the soundtrack."
    email: "atomixflix@gmail.com"
  - name: "Ciera Nicole Sheppard"
    title: "Writer, Vocals & Design"
    image: "images/cns.jpg"
    description: "Writer, Vocalist and Costume Designer - Nicole brings a powerful blend of storytelling, character development, costume design, and epic vocals right where it's needed."
    email: "atomixflix@gmail.com"
  - name: "John Edward Bartholomew Jr"
    title: "Writer, Lyrics & Vocals"
    image: "images/jb.png"
    description: "Lyricist and Creative Contributor, JB owns JB Degustador Panama, a platform that promotes local restaurants, hotels, and mini resorts, fostering growth for Panama’s tourism and hospitality."
    email: "atomixflix@gmail.com"
  - name: "Dulce Petit"
    title: "Writer, Designer & Vocals"
    image: "images/dp.jpg"
    description: "Dulce Petit, videographer and editor for the digital brand JB Degustador, and founder of Panama swimwear brand Bikini Candy Hot, brings a blend of technical discipline, creative vision and visual storytelling."
    email: "atomixflix@gmail.com"
  - name: "Per Thorson"
    title: "Vocalist, Sound Designer, and Producer"
    image: "images/pt.jpg"
    description: "Story Editor and Vocalist - Per is the voice of the AtomicFlix audio books and 'Watchable Storyboard' contributor"
    email: "mechickaboola@gmail.com"
social_links:
  facebook: "https://www.facebook.com/profile.php?id=61593514836175"
  instagram: "https://www.instagram.com/blackrushworld/"
  tiktok: "https://www.tiktok.com/@blackrushworld"
  x: "https://x.com/AtomicFlixCom"
  youtube: "https://youtube.com/blackrush"
  rumble: "https://rumble.com/user/erikleeolson"
  atomicflix: "https://atomicflix.com"